USE [master]
GO

/****** Object:  Database [Online Shop]    Script Date: 15.09.2022 16:09:46 ******/
CREATE DATABASE [Online Shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Online Shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Online Shop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Online Shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Online Shop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Online Shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Online Shop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Online Shop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Online Shop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Online Shop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Online Shop] SET ARITHABORT OFF 
GO

ALTER DATABASE [Online Shop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Online Shop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Online Shop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Online Shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Online Shop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Online Shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Online Shop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Online Shop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Online Shop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Online Shop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Online Shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Online Shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Online Shop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Online Shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Online Shop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Online Shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Online Shop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Online Shop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Online Shop] SET  MULTI_USER 
GO

ALTER DATABASE [Online Shop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Online Shop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Online Shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Online Shop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Online Shop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Online Shop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Online Shop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Online Shop] SET  READ_WRITE 
GO

